import React from 'react';
import { Disclosure, Transition } from '@headlessui/react';

const ChevronUpIcon: React.FC<{ className?: string }> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
    </svg>
);

const faqs = [
  {
    question: "What is the Sovereign Intelligence Index (SII)?",
    answer:
      "The Sovereign Intelligence Index (SII) is a proprietary score generated by our AI engine. It measures your organization's readiness for next-generation technologies, including advanced data intelligence, automation, and quantum integration. It provides a holistic view of your digital maturity across multiple critical domains.",
  },
  {
    question: "How is the SII score calculated?",
    answer:
      "The score is calculated by an advanced AI model that analyzes your answers from the assessment. It weighs your responses across various domains—such as Infrastructure, Data Intelligence, Security, and Governance—and benchmarks them against our extensive dataset of industry best practices and maturity models. The algorithm considers not just individual capabilities but also the interplay between different domains.",
  },
  {
    question: "How long does the assessment take to complete?",
    answer:
      "The comprehensive assessment is designed to be thorough yet efficient. For a user familiar with their organization's technology landscape, it typically takes between 20 to 30 minutes to complete. Your progress is saved automatically, so you can stop and resume at any time.",
  },
  {
    question: "Is my data secure?",
    answer:
      "Absolutely. We take data security and confidentiality with the utmost seriousness. All data is encrypted in transit and at rest. The assessment results are anonymized and aggregated for benchmarking purposes, and your specific company data will never be shared without your explicit consent.",
  },
  {
      question: "What happens after I get my report?",
      answer: "Your report is the starting point. It provides a detailed analysis of your strengths and areas for improvement, along with strategic recommendations. You can use these insights to explore our library of innovation pilots and integration solutions to build a custom, actionable roadmap for your digital transformation journey.",
  }
];

const FaqPage: React.FC = () => {
    return (
        <div className="w-full bg-black/30 backdrop-blur-sm border border-gray-700/50 rounded-2xl shadow-2xl p-6 sm:p-8 animate-fade-in">
            <h1 className="text-3xl font-black text-white text-center mb-12">Frequently Asked Questions</h1>
            <div className="w-full max-w-3xl mx-auto space-y-4">
                {faqs.map((faq, index) => (
                    <Disclosure key={index} as="div" className="bg-gray-800/50 border-2 border-gray-700 rounded-lg">
                        {({ open }) => (
                            <>
                                <Disclosure.Button className="flex justify-between w-full px-6 py-4 text-left text-lg font-medium text-white hover:bg-gray-700/30 focus:outline-none focus-visible:ring focus-visible:ring-blue-500 focus-visible:ring-opacity-75">
                                    <span>{faq.question}</span>
                                    <ChevronUpIcon className={`${open ? 'transform rotate-180' : ''} w-6 h-6 text-blue-400 transition-transform`} />
                                </Disclosure.Button>
                                <Transition
                                    enter="transition duration-100 ease-out"
                                    enterFrom="transform scale-95 opacity-0"
                                    enterTo="transform scale-100 opacity-100"
                                    leave="transition duration-75 ease-out"
                                    leaveFrom="transform scale-100 opacity-100"
                                    leaveTo="transform scale-95 opacity-0"
                                >
                                    <Disclosure.Panel className="px-6 pt-2 pb-4 text-base text-gray-300">
                                        {faq.answer}
                                    </Disclosure.Panel>
                                </Transition>
                            </>
                        )}
                    </Disclosure>
                ))}
            </div>
        </div>
    );
};

export default FaqPage;